 <!--HEADER.PHP-START-->
 
<!DOCTYPE html>
<html lang="en">
<?$APPLICATION->ShowHead()?>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Css -->
    <link rel="stylesheet" type="text/css" href="<?=SITE_TEMPLATE_PATH?>/css/style.css">
   <title><?$APPLICATION->ShowTitle();?></title>
</head>
 <?$APPLICATION->ShowPanel();?>
<body>

    <header id="header" class="header">
       КОНТЕНТ ХЕДЕРА.
	</header>
	
	<!--РАБОЧАЯ ОБЛАСТЬ-START (INDEX.PHP)-->
	<!--РАБОЧАЯ ОБЛАСТЬ-END (INDEX.PHP)-->
	
	<!--ФУТЕР-START (FOOTER.PHP)-->
	<!--ФУТЕР-END (FOOTER.PHP)-->
	