<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("сайт");
?>
 
							<!--КОНТЕНТ РАБОЧЕЙ ОБЛАСТИ- INDEX.PHP START-->
						<div class="slide-item">
						<div class="item-inner">
						<div class="text">
						<h2>Learn more - Earn more</h2>
						<p>this is not only an elegant theme but also<br> a course management system<br> for wordpress and drupal
						</p>
						<div class="group">
						<a href="index.html#" class="mc-btn btn-style-1">See full features</a>
						</div>
						</div>

						<div class="img">
						<img src="<?=SITE_TEMPLATE_PATH?>/images/homeslider/img-thumb.png" alt="">
						</div>
						</div>

						</div> 
						<!--КОНТЕНТ РАБОЧЕЙ ОБЛАСТИ- INDEX.PHP END-->

<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>